<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DeskCore.Shared\DeskCore.Shared.csproj" />
    <ProjectReference Include="..\DeskCore.Domain\DeskCore.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
