<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DeskCore.Domain\DeskCore.Domain.csproj" />
    <ProjectReference Include="..\DeskCore.Shared\DeskCore.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
  </ItemGroup>

</Project>
