<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="Shouldly" Version="4.2.1" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DeskCore.Application\DeskCore.Application.csproj" />
    <ProjectReference Include="..\..\src\DeskCore.Infrastructure\DeskCore.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\DeskCore.Domain\DeskCore.Domain.csproj" />
    <ProjectReference Include="..\..\src\DeskCore.Shared\DeskCore.Shared.csproj" />
  </ItemGroup>

</Project>
